project:
  type: book
  output-dir: docs

execute:
  output: asis
  echo: false

book:  
  language: de
  title: "deckenmalerei"
  author: "ASKCR"
  date: today
  chapters:
    - index.qmd
    - artworks_by_room.ipynb
    - artworks_on_map.ipynb
  #  - intro.qmd
  #  - summary.qmd
  #  - references.qmd
  downloads: [pdf]


bibliography: references.bib

format:
  html:
    theme:
      - solar
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \let\oldincludegraphics\includegraphics
        \renewcommand{\includegraphics}[2][]{%
          \oldincludegraphics[width=\linewidth,height=0.70\textheight,keepaspectratio,#1]{#2}%
        }
    include-after-body: 
      text: |
        \printindex
    #keep-tex: true


