project:
  type: book
  output-dir: docs

execute:
  output: asis
  echo: false

book:
  title: "deckenmalerei"
  author: "ASKCR"
  date: today
  chapters:
    - index.qmd
    - artworks_by_room.ipynb
  #  - intro.qmd
  #  - summary.qmd
  #  - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      - solar
  pdf:
    documentclass: scrreprt



